### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by revast** [NicolaiSoeborg/ELF2deb#5]
elf2deb --license "GPL-3.0" --license_year "2019" --license_holder "Marcel Steinboeck" --package_name "qtox" --package_version "1.16.3-1"  --homepage "https://github.com/qTox/qTox" ./qtox

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/elf2deb/__main__.py", line 204, in <module>
  File "/usr/bin/elf2deb/__main__.py", line 12, in main
  File "/usr/bin/elf2deb/__main__.py", line 183, in get_args
FileNotFoundError: [Errno 2] No such file or directory

I tried with pip3 install, from source and make, and directly executing the .pyz  
- what am I doing wrong?
- maybe a problem with pyhon 3.6?

same with 
~/Downloads/ELF2deb-1.2.0 $ ./elf2deb.pyz elf2deb.pyz
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./elf2deb.pyz/__main__.py", line 204, in <module>
  File "./elf2deb.pyz/__main__.py", line 12, in main
  File "./elf2deb.pyz/__main__.py", line 183, in get_args
FileNotFoundError: [Errno 2] No such file or directory

anyway, nice tool, thanks for creating it!

**Comment by NicolaiSoeborg** [comment]
Thats weird!

What is the result of running this python code:

```python
import os
print(os.getenv("DEBFULLNAME", os.getlogin()))
```

it seems like `DEBFULLNAME` and `DEBEMAIL` might not be set (but they should just default to `<username>` and `mail@example.com`)
